# -*- coding: utf-8 -*-
"""transfer learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vwd6zI_maOP10m1pkkls_nA5dKFt4zRL
"""
from __future__ import absolute_import
from __future__ import unicode_literals
from __future__ import division
from __future__ import print_function

from tl_data_dynamicSS import *
from models import *
from train import args, log_token, model, optimizer

import numpy as np
import torch
import torch.nn as nn
from torch.nn import Parameter
import torch.nn.functional as F
from torch.autograd import Variable
import sys
import os, itertools, random, argparse, time, datetime

model_path = '%s/%s.pt' % (args.save_dir, log_token)
with open(model_path, 'rb') as f:
    checkpoint = torch.load(f);
model.load_state_dict(checkpoint['model_state_dict'])  
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
print("Model's state_dict:")
for param_tensor in model.state_dict():
    print(param_tensor, "\t", model.state_dict()[param_tensor].size())

#print("Optimizer's state_dict:")
#for var_name in optimizer.state_dict():
#    print(var_name, "\t", optimizer.state_dict()[var_name])
#print(model)

state_dict = checkpoint['model_state_dict']
#print(state_dict['conv.weight'])


#########################################################################

import os, itertools, random, argparse, time, datetime
import numpy as np
import random
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score,explained_variance_score
from math import sqrt

import scipy.sparse as sp
from scipy.stats.stats import pearsonr

import shutil
import logging
import glob
import time
from tensorboardX import SummaryWriter

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format='%(asctime)s %(message)s') # include timestamp

# Training settings
ap = argparse.ArgumentParser()
ap.add_argument('--dataset', type=str, default='us-state', help="Dataset string")
ap.add_argument('--sim_mat', type=str, default='us-adj', help="adjacency matrix filename (*-adj.txt)")
ap.add_argument('--vader', type=str, default='vader-score-cosine similarity', help="news (*-news.txt)")
ap.add_argument('--st', type=str, default='st-cosine', help="news (*-news.txt)")
ap.add_argument('--n_layer', type=int, default=1, help="number of layers (default 1)") 
ap.add_argument('--n_hidden', type=int, default=32, help="rnn hidden states (could be set as any value)") 
ap.add_argument('--seed', type=int, default=42, help='random seed')
ap.add_argument('--epochs', type=int, default=1500, help='number of epochs to train')
ap.add_argument('--lr', type=float, default=1e-3, help='initial learning rate')
ap.add_argument('--weight_decay', type=float, default=5e-4, help='weight decay (L2 loss on parameters).')
ap.add_argument('--dropout', type=float, default=0.2, help='dropout rate usually 0.2-0.5.')
ap.add_argument('--batch', type=int, default=32, help="batch size")
ap.add_argument('--check_point', type=int, default=1, help="check point")
ap.add_argument('--shuffle', action='store_true', default=False, help="not used, default false")
ap.add_argument('--train', type=float, default=.8, help="Training ratio (0, 1)")
ap.add_argument('--val', type=float, default=.1, help="Validation ratio (0, 1)")
ap.add_argument('--test', type=float, default=.1, help="Testing ratio (0, 1)")
ap.add_argument('--model', default='cola_gnn', choices=['cola_gnn','CNNRNN_Res','RNN','AR','ARMA','VAR','GAR','SelfAttnRNN','lstnet','stgcn','dcrnn'], help='')
ap.add_argument('--rnn_model', default='RNN', choices=['LSTM','RNN','GRU'], help='')
ap.add_argument('--mylog', action='store_false', default=True,  help='save tensorboad log')
ap.add_argument('--cuda', action='store_true', default=False,  help='')
ap.add_argument('--window', type=int, default=15, help='')
ap.add_argument('--horizon', type=int, default=1, help='leadtime default 1')
ap.add_argument('--save_dir', type=str,  default='save',help='dir path to save the final model')
ap.add_argument('--gpu', type=int, default=3,  help='choose gpu 0-10')
ap.add_argument('--lamda', type=float, default=0.01,  help='regularize params similarities of states')
ap.add_argument('--bi', action='store_true', default=False,  help='bidirectional default false')
ap.add_argument('--patience', type=int, default=200, help='patience default 100')
ap.add_argument('--k', type=int, default=10,  help='kernels')
ap.add_argument('--hidsp', type=int, default=15,  help='spatial dim')

args = ap.parse_args() 
print('--------Parameters--------')
print(args)
print('--------------------------')

os.environ["CUDA_VISIBLE_DEVICES"]=str(args.gpu)

import torch
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader

random.seed(args.seed)
np.random.seed(args.seed)
torch.manual_seed(args.seed)

args.cuda = args.cuda and torch.cuda.is_available() 
logger.info('cuda %s', args.cuda)

time_token = str(time.time()).split('.')[0] # tensorboard model
log_token = '%s.%s.w-%s.h-%s.%s' % (args.model, args.dataset, args.window, args.horizon, args.rnn_model)

if args.mylog:
    tensorboard_log_dir = 'tensorboard/%s' % (log_token)
    if not os.path.exists(tensorboard_log_dir):
        os.makedirs(tensorboard_log_dir)
    writer = SummaryWriter(tensorboard_log_dir)
    shutil.rmtree(tensorboard_log_dir)
    logger.info('tensorboard logging to %s', tensorboard_log_dir)
 
############Model Start##########
TLdata_loader = TLData_Loader(args)
TLmodel = TLDynamic_SS(args, TLdata_loader)


with torch.no_grad(): 
  TLmodel.conv.weight.copy_(state_dict['conv.weight'])#.requires_grad=False
  #print(TLmodel.conv.weight)
  TLmodel.conv.bias.copy_(state_dict['conv.bias'])#.requires_grad=False
  TLmodel.conv_long.weight.copy_(state_dict['conv_long.weight'])#.requires_grad=False
  TLmodel.conv_long.bias.copy_(state_dict['conv_long.bias'])#.requires_grad=False
#  TLmodel.conv1.weight.copy_(state_dict['conv1.weight']).requires_grad=False
#  TLmodel.conv1.bias.copy_(state_dict['conv1.bias']).requires_grad=False
#  TLmodel.conv2.weight.copy_(state_dict['conv2.weight']).requires_grad=False
#  TLmodel.conv2.bias.copy_(state_dict['conv2.bias']).requires_grad=False
#  TLmodel.rnn.weight_ih_l0 .copy_(state_dict['rnn.weight_ih_l0']).requires_grad=False
#  TLmodel.rnn.bias_ih_l0.copy_(state_dict['rnn.bias_ih_l0']).requires_grad=False
#  TLmodel.rnn.weight_hh_l0 .copy_(state_dict['rnn.weight_hh_l0']).requires_grad=False
#  TLmodel.rnn.bias_hh_l0.copy_(state_dict['rnn.bias_hh_l0']).requires_grad=False
for param_tensor in TLmodel.state_dict():
    print(param_tensor, "\t", TLmodel.state_dict()[param_tensor].size())


logger.info('model %s', TLmodel)
if args.cuda:
    TLmodel.cuda()
optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, TLmodel.parameters()), lr=args.lr, weight_decay=args.weight_decay)
pytorch_total_params = sum(p.numel() for p in TLmodel.parameters() if p.requires_grad)
print('#params:',pytorch_total_params)

def evaluate(TLdata_loader, data, tag='val'):
    TLmodel.eval()
    total = 0.
    n_samples = 0.
    total_loss = 0.
    y_true, y_pred = [], []
    batch_size = args.batch
    y_pred_mx = []
    y_true_mx = []
    for inputs in TLdata_loader.get_batches(data, batch_size, False):
        X, X2, X3, X4, Y = inputs[0], inputs[1], inputs[2], inputs[3], inputs[4]
        output,_ = TLmodel(X, X2, X3, X4)
        loss_train = F.l1_loss(output, Y) # mse_loss
        total_loss += loss_train.item()
        n_samples += (output.size(0) * TLdata_loader.m);

        y_true_mx.append(Y.data.cpu())
        y_pred_mx.append(output.data.cpu())

    y_pred_mx = torch.cat(y_pred_mx)
    y_true_mx = torch.cat(y_true_mx) # [n_samples, 47] 
    y_true_states = y_true_mx.numpy() * (TLdata_loader.max - TLdata_loader.min ) * 1.0 + TLdata_loader.min  
    y_pred_states = y_pred_mx.numpy() * (TLdata_loader.max - TLdata_loader.min ) * 1.0 + TLdata_loader.min  #(#n_samples, 47)
    rmse_states = np.mean(np.sqrt(mean_squared_error(y_true_states, y_pred_states, multioutput='raw_values'))) # mean of 47
    raw_mae = mean_absolute_error(y_true_states, y_pred_states, multioutput='raw_values')
    std_mae = np.std(raw_mae) # Standard deviation of MAEs for all states/places 
    pcc_tmp = []
    for k in range(TLdata_loader.m):
        pcc_tmp.append(pearsonr(y_true_states[:,k],y_pred_states[:,k])[0])
    pcc_states = np.mean(np.array(pcc_tmp)) 
    r2_states = np.mean(r2_score(y_true_states, y_pred_states, multioutput='raw_values'))
    var_states = np.mean(explained_variance_score(y_true_states, y_pred_states, multioutput='raw_values'))

    # convert y_true & y_pred to real data
    y_true = np.reshape(y_true_states,(-1))
    y_pred = np.reshape(y_pred_states,(-1))
    rmse = sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    pcc = pearsonr(y_true,y_pred)[0]
    r2 = r2_score(y_true, y_pred,multioutput='uniform_average') #variance_weighted 
    var = explained_variance_score(y_true, y_pred, multioutput='uniform_average')
    peak_mae = peak_error(y_true_states.copy(), y_pred_states.copy(), TLdata_loader.peak_thold)
    global y_true_t
    global y_pred_t
    y_true_t = y_true_states
    y_pred_t = y_pred_states
    # save prediction values for further tests
    np.savetxt("/content/ypred.txt",y_pred)
    return float(total_loss / n_samples), mae,std_mae, rmse, rmse_states, pcc, pcc_states, r2, r2_states, var, var_states, peak_mae

def train(TLdata_loader, data):
    #print(TLmodel.conv.weight)
    TLmodel.train()
    total_loss = 0.
    n_samples = 0.
    batch_size = args.batch

    for inputs in TLdata_loader.get_batches(data, batch_size, True):
        X, X2, X3, X4, Y = inputs[0], inputs[1], inputs[2], inputs[3], inputs[4]
        optimizer.zero_grad()
        #optimizer.requires_grad = True
        output,_ = TLmodel(X, X2, X3, X4) 
        if Y.size(0) == 1:
            Y = Y.view(-1)
        loss_train = F.l1_loss(output, Y) # mse_loss
        total_loss += loss_train.item()
        loss_train.backward()
        optimizer.step()
        n_samples += (output.size(0) * TLdata_loader.m)
    return float(total_loss / n_samples)
 
bad_counter = 0
best_epoch = 0
best_val = 1e+20;
try:
    print('begin training');
    if not os.path.exists(args.save_dir):
        os.makedirs(args.save_dir)
    
    for epoch in range(1, args.epochs+1):
        epoch_start_time = time.time()
        train_loss = train(TLdata_loader, TLdata_loader.train)
        val_loss, mae,std_mae, rmse, rmse_states, pcc, pcc_states, r2, r2_states, var, var_states, peak_mae = evaluate(TLdata_loader, TLdata_loader.val)
        print('Epoch {:3d}|time:{:5.2f}s|train_loss {:5.8f}|val_loss {:5.8f}'.format(epoch, (time.time() - epoch_start_time), train_loss, val_loss))

        if args.mylog:
            writer.add_scalars('data/loss', {'train': train_loss}, epoch )
            writer.add_scalars('data/loss', {'val': val_loss}, epoch)
            writer.add_scalars('data/mae', {'val': mae}, epoch)
            writer.add_scalars('data/rmse', {'val': rmse_states}, epoch)
            writer.add_scalars('data/rmse_states', {'val': rmse_states}, epoch)
            writer.add_scalars('data/pcc', {'val': pcc}, epoch)
            writer.add_scalars('data/pcc_states', {'val': pcc_states}, epoch)
            writer.add_scalars('data/R2', {'val': r2}, epoch)
            writer.add_scalars('data/R2_states', {'val': r2_states}, epoch)
            writer.add_scalars('data/var', {'val': var}, epoch)
            writer.add_scalars('data/var_states', {'val': var_states}, epoch)
            writer.add_scalars('data/peak_mae', {'val': peak_mae}, epoch)
       
        # Save the model if the validation loss is the best we've seen so far.
        if val_loss < best_val:
            best_val = val_loss
            best_epoch = epoch
            bad_counter = 0
            model_path = '%s/%s.pt' % (args.save_dir, log_token)
            with open(model_path, 'wb') as f:
                torch.save({'model_state_dict': TLmodel.state_dict(),
                            'optimizer_state_dict': optimizer.state_dict()}, f)
            print('Best validation epoch:',epoch, time.ctime());
            test_loss, mae,std_mae, rmse, rmse_states, pcc, pcc_states, r2, r2_states, var, var_states, peak_mae  = evaluate(TLdata_loader, TLdata_loader.test,tag='test')
            print('TEST MAE {:5.4f} std {:5.4f} RMSE {:5.4f} RMSEs {:5.4f} PCC {:5.4f} PCCs {:5.4f} R2 {:5.4f} R2s {:5.4f} Var {:5.4f} Vars {:5.4f} Peak {:5.4f}'.format( mae, std_mae, rmse, rmse_states, pcc, pcc_states,r2, r2_states, var, var_states, peak_mae))
        else:
            bad_counter += 1

        if bad_counter == args.patience:
            break

except KeyboardInterrupt:
    print('-' * 89)
    print('Exiting from training early, epoch',epoch)

# Load the best saved model.
model_path = '%s/%s.pt' % (args.save_dir, log_token)
with open(model_path, 'rb') as f:
    checkpoint = torch.load(f);
TLmodel.load_state_dict(checkpoint['model_state_dict'])  
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
test_loss, mae,std_mae, rmse, rmse_states, pcc, pcc_states, r2, r2_states, var, var_states, peak_mae  = evaluate(TLdata_loader, TLdata_loader.test,tag='test')
print('Final evaluation')
print('TEST MAE {:5.4f} std {:5.4f} RMSE {:5.4f} RMSEs {:5.4f} PCC {:5.4f} PCCs {:5.4f} R2 {:5.4f} R2s {:5.4f} Var {:5.4f} Vars {:5.4f} Peak {:5.4f}'.format( mae, std_mae, rmse, rmse_states, pcc, pcc_states,r2, r2_states, var, var_states, peak_mae))
